unstable_features = true

edition = "2024"

wrap_comments = false
where_single_line = true
use_try_shorthand = false
use_small_heuristics = "Default"
use_field_init_shorthand = true
type_punctuation_density = "Wide"
trailing_semicolon = true
trailing_comma = "Vertical"
tab_spaces = 4
struct_variant_width = 35
struct_lit_width = 18
struct_lit_single_line = false
struct_field_align_threshold = 0
spaces_around_ranges = false
space_before_colon = false
space_after_colon = true
single_line_let_else_max_width = 0
single_line_if_else_max_width = 0
short_array_element_width_threshold = 10
reorder_modules = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_impl_items = true
remove_nested_parens = true
overflow_delimited_expr = true
normalize_doc_attributes = true
normalize_comments = false
newline_style = "Auto"
imports_granularity = "Crate"
merge_derives = true
max_width = 140
match_block_trailing_comma = true
match_arm_leading_pipes = "Preserve"
match_arm_blocks = true
inline_attribute_width = 0
indent_style = "Block"
imports_layout = "Vertical"
hard_tabs = false
format_code_in_doc_comments = true
force_multiline_blocks = false
force_explicit_abi = true
fn_single_line = false
fn_params_layout = "Tall"
empty_item_single_line = false
control_brace_style = "AlwaysSameLine"
brace_style = "PreferSameLine"
blank_lines_upper_bound = 1
binop_separator = "Front"
